title: Wayverb
email: reuben.thomas@me.com
description: >
    Wayverb does realistic, fast acoustic simulations.
    It's useful for creating beautiful custom reverbs for your compositions, or
    for checking the acoustics of architecture, without actually building
    anything!
    It's also free and open source.
baseurl: "/wayverb"

# Plugins
gems:
- jekyll-pandoc

# Build settings
markdown: Pandoc

pandoc:
    extensions:
    - csl: elsevier-with-titles.csl
    - bibliography: wayverb.bib

exclude:
- LICENSE.txt
- readme.txt
- todo.md
