# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Wayverb
email: reuben.thomas@me.com
description: >
    Wayverb does realistic, fast acoustic simulations.
    It's useful for creating beautiful custom reverbs for your compositions, or
    for checking the acoustics of architecture, without actually building
    anything!
    It's also free and open source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Plugins
gems:
  - jekyll-pandoc

# Build settings
markdown: Pandoc
